
services:
  mysql:
    image : mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenseapp
    ports: 
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - expenseapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  expenseapp:
    build: 
      context: .
    container_name: expenseapp
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenseapp?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_PASSWORD: root
    ports: 
      - "8080:8080"
    networks:
      - expenseapp-network
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql-data:
networks:
  expenseapp-network: